# Generated by Django 5.0.1 on 2024-04-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0007_alter_visitcounter_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitcounter',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
