# Generated by Django 5.0.1 on 2024-04-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0008_alter_visitcounter_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('mes_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(default='null', max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
