# Generated by Django 5.0.1 on 2024-05-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0009_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
